name: 'Local project dependency diff diagram for Gradle'
description: "Generates a dependency diff diagram between 2 commits"
inputs:
  configuration:
    description: 'Selected Gradle configuration, passed to `./gradlew -q <app>:dependencies --configuration <configuration>`. Should correspond to output artifact that is considered output of the project'
    required: false
    default: 'releaseRuntimeClasspath'
  project:
    description: 'Project'
    required: false
    default: 'app'
  build-root-directory:
    description: 'Build root directory'
    required: false
    default: .
  additional-gradle-arguments:
    description: 'Additional arguments passed to gradle commands'
    required: false
    default: ''
outputs:
  diff-image-file:
    description: "Dependency diff"
    value: ${{ steps.diff-generator.outputs.diff-image-file }}
branding:
  color: 'red'
  icon: 'check-square'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - id: diff-generator
      env:
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_CONFIGURATION: ${{ inputs.configuration }}
        INPUT_BASEREF: ${{ github.base_ref }}
        INPUT_MERGEREF: ${{ github.sha }}
        INPUT_BUILD_ROOT_DIR: ${{ inputs.build-root-directory }}
        ADDITIONAL_GRADLE_ARGUMENTS: ${{ inputs.additional-gradle-arguments }}
        ACTION_PATH: ${{ github.action_path }}
      shell: bash
      run: |
        ORIGINAL=$PWD

        cd "$INPUT_BUILD_ROOT_DIR"

        ./gradlew $ADDITIONAL_GRADLE_ARGUMENTS -q "$INPUT_PROJECT":dependencies --configuration "$INPUT_CONFIGURATION" > "$ORIGINAL/new_diff.txt"
        git fetch --force origin "$INPUT_BASEREF":"$INPUT_BASEREF" --no-tags
        git switch --force "$INPUT_BASEREF"
        ./gradlew $ADDITIONAL_GRADLE_ARGUMENTS -q "$INPUT_PROJECT":dependencies --configuration "$INPUT_CONFIGURATION" > "$ORIGINAL/old_diff.txt"
        
        # Restore the original checkout
        git fetch --force origin "$INPUT_MERGEREF":"$INPUT_MERGEREF" --no-tags
        git switch --force "$INPUT_MERGEREF"

        cd -

        python main.py diff old_diff.txt new_diff.txt -o diff.png
        
        if [[ -f "diff.png" ]]; then
          echo "File exists, there was a diff"
          echo "diff-image-file=diff.png" >> $GITHUB_OUTPUT
        else
          echo "File does not exist, there was no diff"
        fi
    - uses: actions/upload-artifact@v3
      id: upload
      with:
        name: Dependency_Diff.png
        path:
          ./diff.png
